{{- if .Values.persistent.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistent.name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistent.storage }}
  storageClassName: {{ .Values.persistent.storageClassName }}
  volumeMode: Filesystem
{{- end }}